info:
  app:
    name: 业务系统例子服务UI
    description: 用来做相关例子的
    version: 1.0.0.100
    #此ui依赖的service的服务名称，用于在@FeignClient中
    service:
      name: example-service
      #就是service的server.servlet.context-path，去掉“/”
      prefix: "example-service"
server:
  port: 9980
  servlet:
    context-path: "/example-ui"


spring:
  application:
    name: example-ui
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 5
        min-idle: 5
        max-idle: 5
        max-wait: 5
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000
  activemq:
    broker-url: tcp://192.168.223.129:61616
  servlet:
    multipart:
      enabled: true
      # 单个文件大小，默认1MB
      max-file-size: 1MB
      # 所有文件总大小，默认10MB
      max-request-size: 10MB
      # 超过这个数值，文件将会被写入到磁盘，默认0B
      file-size-threshold: 10KB
      # 文件临时存储位置，注意，路径要用//，不能用\
      # location: "F://testFile//fileUpload"

eureka:
  client:
    service-url:
      #defaultZone: http://192.168.1.105:8761/eureka/
      defaultZone: http://192.168.223.129:8761/eureka/
  instance:
    ip-address: 192.168.223.1


#多租户相关
multiple-tenant:
  tenant: tenant1
  weight: 2
  label-and: aa,bb
  label-or: ee

feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
thread-pool:
  core-pool-size: 5
  max-pool-size: 7
  queue-capacity: 1

