info:
  app:
    name: 业务系统例子服务Service
    description: 用来做相关例子的
    version: 1.0.0.100

server:
  port: 9981
  servlet:
    context-path: "/example-service"

spring:
  application:
    name: example-service
  profiles:
    active: dev
  datasource:
    # flyway使用这个参数，多数据源不需要配置此属性，支持oracle, mysql
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.136:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: ENC(tXVsX2fiUQfrNM9Gqey3pmRiLgw+Znp/ISEaZCOMDo0=)
    # 连接池属性配置见https://github.com/brettwooldridge/HikariCP，以下几个是常用的
    hikari:
      connection-timeout: 30001
      idle-timeout: 600001
      max-lifetime: 1800001
      maximum-pool-size: 11
      minimum-idle: 11
    one:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.223.136:3306/milepost_auth_1?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: ENC(tXVsX2fiUQfrNM9Gqey3pmRiLgw+Znp/ISEaZCOMDo0=)
      hikari:
        connection-timeout: 30002
        idle-timeout: 600002
        max-lifetime: 1800002
        maximum-pool-size: 12
        minimum-idle: 12
    two:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.223.136:3306/milepost_auth_2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: ENC(tXVsX2fiUQfrNM9Gqey3pmRiLgw+Znp/ISEaZCOMDo0=)
      hikari:
        connection-timeout: 30003
        idle-timeout: 600003
        max-lifetime: 1800003
        maximum-pool-size: 13
        minimum-idle: 13
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 20
        min-idle: 10
        max-idle: 20
        max-wait: 2000
    #配置redis服务器属性
    database: 1
    host: 192.168.223.136
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000
  flyway:
    enabled: true
  activemq:
    broker-url: tcp://192.168.223.136:61616
  # web登录地址http://192.168.223.136:15672   admin/admin
  rabbitmq:
    #rabbitmq服务器ip
    host: 192.168.223.136
    #rabbitmq端口
    port: 5672
    #rabbitmq用户
    username: admin
    #rabbitmq密码
    password: admin
#    #是否确认发送的消息已经被消费
#    publisher-confirms: true
#  cloud:
#    bus:
#      id: example-service
#      trace:
#        enabled: true
  # 开启
#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      # 跟踪采样率，0--1，默认是 0.1
#      probability: 1.0
#  zipkin:
#    sender:
#      type: rabbit
  # 关闭
#  sleuth:
#    enabled: false
#  zipkin:
#    enabled: false
track:
  enabled: true
  sampling: 0.1

eureka:
  client:
    service-url:
      #defaultZone: http://192.168.1.105:8761/eureka/
      defaultZone: http://192.168.223.136:8761/eureka/
  instance:
    ip-address: 192.168.223.1
    #${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    #instance-id: xxx

#为了EurekaServer更灵敏而加的
#eureka.instance.lease-renewal-interval-in-seconds: 4
#eureka.instance.lease-expiration-duration-in-seconds: 7

#multiple-tenant:
#  tenant: abc
#  weight: 1
#  label-and: aa,bb
#  label-or: aa

#multiple-tenant:
#  tenant: abc
#  weight: 9
#  label-and: aa,bb

#multiple-tenant:
#  tenant: abc
#  weight: 0
#  label-and: aa,bb

multiple-tenant:
  tenant: tenant1
  weight: 9
  label-and: aa,bb
  label-or: dd,ee,ff


feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000

conditional:
  rand:
    type: boolean
  demo:
    load: false
  property: properExists
  express: true

scheduler-lock:
  # 是否启用分布式调度锁，默认true，即启用，如不启用则不能使用@SchedulerLock、InstanceRoleService。
  enabled: true
  touch-heartbeat-interval-in-milliseconds: 15000
  heartbeat-expiration-duration-in-seconds: 45
synchronized-lock:
  # 是否启用分布式同步锁，默认true，即启用，如不启用则不能使用@SynchronizedLock。
  enabled: true
  # 分布式同步锁重试获取锁的间隔时间，即每隔多久重试一次是否有其他实例正占有锁，默认1000ms。
  retry-interval-in-milliseconds: 1000
  # 每一个实例能占有锁的最长时间，默认45s
  hold-duration-in-seconds: 45
thread-pool:
  core-pool-size: 3
  max-pool-size: 5
  queue-capacity: 1
  keep-alive-seconds: 600

tx-lcn:
  client:
    manager-address: 192.168.223.136:8070

#hystrix:
#  command:
#    test2:
##      execution:
##        timeout:
##          #开启线程执行超时，默认true
##          enabled: true
##        isolation:
##          #hystrix资源隔离策略，THREAD(线程池)、SEMAPHORE(信号量)，默认THREAD
##          strategy: THREAD
##          thread:
##            #hystrix线程执行超时时间，默认1000
##            timeoutInMilliseconds: 1000
##            #发生超时时，hystrix线程是否终止，默认true
##            interruptOnTimeout: true
##            #取消请求时，hystrix线程是否终止，默认false
##            interruptOnCancel: false
#      fallback:
#        #开启fallback，影响@FeignClient和           ？？？？@HystrixCommand的fallback，默认true
#        enabled: true
#      circuitBreaker:
#        #开启断路器功能(一段时间内失败的请求太多时@FeignClient和@HystrixCommand自动进入fallback逻辑的功能)，默认true
#        enabled: true
#        #滚动时间窗口内，失败请求数超过此数则断路器开启，默认20
#        requestVolumeThreshold: 2
#        #失败百分比，滚动时间窗口内，失败请求数这个百分比则断路器开启，默认50
#        errorThresholdPercentage: 50
#        #断路器开启后，超过此时间后尝试一次，如请求正常了，则关闭断路器，默认5000
#        sleepWindowInMilliseconds: 10000
#      metrics:
#        rollingStats:
#          #滚动时间窗口大小，默认10000
#          timeInMilliseconds: 10000



management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
